name: TryHackMe CI

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.14
        uses: actions/setup-python@v5
        with:
          python-version: '3.14'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Setup Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      - name: Run Pytest
        env:
          BASE_URL: ${{ secrets.BASE_URL }}
          TEST_LOGIN: ${{ secrets.TEST_LOGIN }}
          TEST_PASSWORD: ${{ secrets.TEST_PASSWORD }}
          TEST_USERNAME: ${{ secrets.TEST_USERNAME }}
          AUTH_COOKIE: ${{ secrets.AUTH_COOKIE }}
          INVALID_TEST_LOGIN: ${{ secrets.INVALID_TEST_LOGIN }}
          INVALID_TEST_PASSWORD: ${{ secrets.INVALID_TEST_PASSWORD }}
          PYTHONPATH: ${{ github.workspace }}
        run: |
          pytest alex_talako/pom_site/test/ \
          --alluredir=allure-results | tee pytest_result.txt
          SUMMARY=$(grep -E 'passed|failed|error' pytest_result.txt | tail -n 1 | tr -d '=')
          echo "PYTEST_SUMMARY=$SUMMARY" >> $GITHUB_ENV
        continue-on-error: true

      - name: Save Allure Results
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: allure-results
          retention-days: 1

      - name: Notify Telegram
        if: always()
        run: |
            curl -s -X POST https://api.telegram.org/bot${{ secrets.BOT_TOKEN }}/sendMessage \
              -d chat_id=${{ secrets.TELEGRAM_CHAT_ID }} \
              -d text="🚀 CI Статус: Тесты в облаке завершены!%0A%0A📊 Итог: ${{ env.PYTEST_SUMMARY }}%0A%0A☁️ Результаты в Artifacts. /full_report"
